import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const ROLE_PERMISSIONS = [
  {
    role: 'super_admin',
    label: 'Super Admin',
    color: '#7C3AED',
    permissions: {
      // Dashboard
      dashboard_view: true,
      dashboard_stats_all: true,
      // Staff
      staff_view: true,
      staff_create: true,
      staff_edit: true,
      staff_delete: true,
      staff_manage_roles: true,
      // Applications
      applications_view: true,
      applications_view_all: true,
      applications_create: true,
      applications_edit: true,
      applications_delete: true,
      applications_assign: true,
      applications_approve: true,
      // Visa
      visa_view: true,
      visa_view_all: true,
      visa_create: true,
      visa_edit: true,
      visa_delete: true,
      visa_approve: true,
      // Trips / Trip Planner
      trips_view: true,
      trips_view_all: true,
      trips_create: true,
      trips_edit: true,
      trips_delete: true,
      trips_assign: true,
      trips_proposals: true,
      // Bookings
      bookings_view: true,
      bookings_view_all: true,
      bookings_create: true,
      bookings_edit: true,
      bookings_delete: true,
      // Payments
      payments_view: true,
      payments_view_all: true,
      payments_create: true,
      payments_edit: true,
      payments_delete: true,
      payments_refund: true,
      // Reports
      reports_view: true,
      reports_all: true,
      reports_revenue: true,
      reports_staff: true,
      reports_export: true,
      // Settings
      settings_view: true,
      settings_edit: true,
      settings_roles: true,
      settings_integrations: true,
      // CMS
      cms_view: true,
      cms_edit: true,
      cms_publish: true,
      // Notifications
      notifications_view: true,
      notifications_send: true,
      notifications_broadcast: true,
    },
  },
  {
    role: 'general_manager',
    label: 'General Manager',
    color: '#0B1F3A',
    permissions: {
      dashboard_view: true,
      dashboard_stats_all: true,
      staff_view: true,
      staff_create: false,
      staff_edit: true,
      staff_delete: false,
      staff_manage_roles: false,
      applications_view: true,
      applications_view_all: true,
      applications_create: true,
      applications_edit: true,
      applications_delete: false,
      applications_assign: true,
      applications_approve: true,
      visa_view: true,
      visa_view_all: true,
      visa_create: true,
      visa_edit: true,
      visa_delete: false,
      visa_approve: true,
      trips_view: true,
      trips_view_all: true,
      trips_create: true,
      trips_edit: true,
      trips_delete: false,
      trips_assign: true,
      trips_proposals: true,
      bookings_view: true,
      bookings_view_all: true,
      bookings_create: true,
      bookings_edit: true,
      bookings_delete: false,
      payments_view: true,
      payments_view_all: true,
      payments_create: true,
      payments_edit: true,
      payments_delete: false,
      payments_refund: true,
      reports_view: true,
      reports_all: true,
      reports_revenue: true,
      reports_staff: true,
      reports_export: true,
      settings_view: true,
      settings_edit: false,
      settings_roles: false,
      settings_integrations: false,
      cms_view: true,
      cms_edit: true,
      cms_publish: true,
      notifications_view: true,
      notifications_send: true,
      notifications_broadcast: true,
    },
  },
  {
    role: 'senior_manager',
    label: 'Senior Manager',
    color: '#C9A84C',
    permissions: {
      dashboard_view: true,
      dashboard_stats_all: false,
      staff_view: true,
      staff_create: false,
      staff_edit: false,
      staff_delete: false,
      staff_manage_roles: false,
      applications_view: true,
      applications_view_all: true,
      applications_create: true,
      applications_edit: true,
      applications_delete: false,
      applications_assign: true,
      applications_approve: true,
      visa_view: true,
      visa_view_all: true,
      visa_create: true,
      visa_edit: true,
      visa_delete: false,
      visa_approve: true,
      trips_view: true,
      trips_view_all: true,
      trips_create: true,
      trips_edit: true,
      trips_delete: false,
      trips_assign: true,
      trips_proposals: true,
      bookings_view: true,
      bookings_view_all: true,
      bookings_create: true,
      bookings_edit: true,
      bookings_delete: false,
      payments_view: true,
      payments_view_all: false,
      payments_create: false,
      payments_edit: false,
      payments_delete: false,
      payments_refund: false,
      reports_view: true,
      reports_all: false,
      reports_revenue: false,
      reports_staff: false,
      reports_export: true,
      settings_view: false,
      settings_edit: false,
      settings_roles: false,
      settings_integrations: false,
      cms_view: true,
      cms_edit: true,
      cms_publish: false,
      notifications_view: true,
      notifications_send: true,
      notifications_broadcast: false,
    },
  },
  {
    role: 'coordinator',
    label: 'Coordinator',
    color: '#2563EB',
    permissions: {
      dashboard_view: true,
      dashboard_stats_all: false,
      staff_view: false,
      staff_create: false,
      staff_edit: false,
      staff_delete: false,
      staff_manage_roles: false,
      applications_view: true,
      applications_view_all: false,
      applications_create: true,
      applications_edit: true,
      applications_delete: false,
      applications_assign: false,
      applications_approve: false,
      visa_view: true,
      visa_view_all: false,
      visa_create: true,
      visa_edit: true,
      visa_delete: false,
      visa_approve: false,
      trips_view: true,
      trips_view_all: false,
      trips_create: true,
      trips_edit: true,
      trips_delete: false,
      trips_assign: false,
      trips_proposals: true,
      bookings_view: true,
      bookings_view_all: false,
      bookings_create: true,
      bookings_edit: true,
      bookings_delete: false,
      payments_view: true,
      payments_view_all: false,
      payments_create: false,
      payments_edit: false,
      payments_delete: false,
      payments_refund: false,
      reports_view: true,
      reports_all: false,
      reports_revenue: false,
      reports_staff: false,
      reports_export: false,
      settings_view: false,
      settings_edit: false,
      settings_roles: false,
      settings_integrations: false,
      cms_view: false,
      cms_edit: false,
      cms_publish: false,
      notifications_view: true,
      notifications_send: false,
      notifications_broadcast: false,
    },
  },
  {
    role: 'sales_rep',
    label: 'Sales Representative',
    color: '#16A34A',
    permissions: {
      dashboard_view: true,
      dashboard_stats_all: false,
      staff_view: false,
      staff_create: false,
      staff_edit: false,
      staff_delete: false,
      staff_manage_roles: false,
      applications_view: true,
      applications_view_all: false,
      applications_create: true,
      applications_edit: true,
      applications_delete: false,
      applications_assign: false,
      applications_approve: false,
      visa_view: true,
      visa_view_all: false,
      visa_create: true,
      visa_edit: true,
      visa_delete: false,
      visa_approve: false,
      trips_view: true,
      trips_view_all: false,
      trips_create: true,
      trips_edit: true,
      trips_delete: false,
      trips_assign: false,
      trips_proposals: false,
      bookings_view: true,
      bookings_view_all: false,
      bookings_create: true,
      bookings_edit: false,
      bookings_delete: false,
      payments_view: true,
      payments_view_all: false,
      payments_create: false,
      payments_edit: false,
      payments_delete: false,
      payments_refund: false,
      reports_view: false,
      reports_all: false,
      reports_revenue: false,
      reports_staff: false,
      reports_export: false,
      settings_view: false,
      settings_edit: false,
      settings_roles: false,
      settings_integrations: false,
      cms_view: false,
      cms_edit: false,
      cms_publish: false,
      notifications_view: true,
      notifications_send: false,
      notifications_broadcast: false,
    },
  },
]

async function main() {
  console.log('🌱 Seeding role permissions...')

  for (const rp of ROLE_PERMISSIONS) {
    await prisma.rolePermission.upsert({
      where:  { role: rp.role },
      update: { label: rp.label, color: rp.color, permissions: rp.permissions },
      create: rp,
    })
    console.log(`  ✅ ${rp.label} (${rp.role})`)
  }

  console.log('\n✨ Role permissions seeded successfully.')
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
