import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const T = true
const F = false

const ROLE_PERMISSIONS = [
  {
    role:  'super_admin',
    label: 'Super Admin',
    color: '#7C3AED',
    permissions: {
      dashboard_view: T, dashboard_stats_all: T,
      clients_view: T, clients_create: T, clients_edit: T, clients_delete: T,
      leads_view: T, leads_manage: T,
      bookings_view: T, bookings_view_all: T, bookings_create: T, bookings_edit: T, bookings_cancel: T, bookings_delete: T,
      flights_search: T, flight_deals_view: T, ticket_generator: T, itinerary_planner: T, transfers_view: T,
      trips_view: T, trips_view_all: T, trips_create: T, trips_edit: T, trips_delete: T, trips_assign: T, trips_proposals: T,
      visa_view: T, visa_view_all: T, visa_own: T, visa_create: T, visa_edit: T, visa_approve: T, visa_delete: T,
      visa_send_form: T, visa_form_tracker: T, visa_bank_analyser: T, visa_intelligence: T,
      payments_view: T, payments_view_all: T, payments_create: T, payments_manage: T, payments_edit: T, payments_refund: T, payments_delete: T,
      accounting_view: T, accounting_export: T, invoices_view: T, invoices_create: T, invoices_send: T,
      payroll_view: T, payroll_run: T,
      reports_view: T, reports_submit: T, reports_all: T, reports_revenue: T, reports_staff: T, reports_export: T,
      staff_view: T, staff_create: T, staff_edit: T, staff_delete: T, staff_manage_roles: T,
      applications_view: T, applications_view_all: T, applications_create: T, applications_edit: T, applications_delete: T, applications_assign: T, applications_approve: T,
      inbox_view: T, inbox_reply: T, inbox_assign: T, inbox_delete: T,
      notifications_view: T, notifications_send: T, notifications_broadcast: T,
      destinations_view: T, destinations_edit: T, hotel_promos_view: T, hotel_promos_edit: T, flight_extras_view: T, jade_miles_view: T,
      cms_view: T, cms_edit: T, cms_publish: T,
      roles_view: T, roles_manage: T, roles_assign: T,
      settings_view: T, settings_edit: T, settings_roles: T, settings_integrations: T,
    },
  },
  {
    role:  'operations_manager',
    label: 'Operations Manager',
    color: '#2563EB',
    permissions: {
      dashboard_view: T, dashboard_stats_all: T,
      clients_view: T, clients_create: T, clients_edit: T, clients_delete: F,
      leads_view: T, leads_manage: T,
      bookings_view: T, bookings_view_all: T, bookings_create: T, bookings_edit: T, bookings_cancel: T, bookings_delete: F,
      flights_search: T, flight_deals_view: T, ticket_generator: T, itinerary_planner: T, transfers_view: T,
      trips_view: T, trips_view_all: T, trips_create: T, trips_edit: T, trips_delete: F, trips_assign: T, trips_proposals: T,
      visa_view: T, visa_view_all: T, visa_own: T, visa_create: T, visa_edit: T, visa_approve: T, visa_delete: F,
      visa_send_form: T, visa_form_tracker: T, visa_bank_analyser: T, visa_intelligence: T,
      payments_view: T, payments_view_all: T, payments_create: T, payments_manage: T, payments_edit: T, payments_refund: T, payments_delete: F,
      accounting_view: T, accounting_export: T, invoices_view: T, invoices_create: T, invoices_send: T,
      payroll_view: T, payroll_run: F,
      reports_view: T, reports_submit: T, reports_all: T, reports_revenue: T, reports_staff: T, reports_export: T,
      staff_view: T, staff_create: T, staff_edit: T, staff_delete: F, staff_manage_roles: F,
      applications_view: T, applications_view_all: T, applications_create: T, applications_edit: T, applications_delete: F, applications_assign: T, applications_approve: T,
      inbox_view: T, inbox_reply: T, inbox_assign: T, inbox_delete: F,
      notifications_view: T, notifications_send: T, notifications_broadcast: T,
      destinations_view: T, destinations_edit: T, hotel_promos_view: T, hotel_promos_edit: T, flight_extras_view: T, jade_miles_view: T,
      cms_view: T, cms_edit: T, cms_publish: T,
      roles_view: T, roles_manage: F, roles_assign: F,
      settings_view: T, settings_edit: F, settings_roles: F, settings_integrations: F,
    },
  },
  {
    role:  'general_manager',
    label: 'General Manager',
    color: '#0B1F3A',
    permissions: {
      dashboard_view: T, dashboard_stats_all: T,
      clients_view: T, clients_create: T, clients_edit: T, clients_delete: F,
      leads_view: T, leads_manage: T,
      bookings_view: T, bookings_view_all: T, bookings_create: T, bookings_edit: T, bookings_cancel: T, bookings_delete: F,
      flights_search: T, flight_deals_view: T, ticket_generator: T, itinerary_planner: T, transfers_view: T,
      trips_view: T, trips_view_all: T, trips_create: T, trips_edit: T, trips_delete: F, trips_assign: T, trips_proposals: T,
      visa_view: T, visa_view_all: T, visa_own: T, visa_create: T, visa_edit: T, visa_approve: T, visa_delete: F,
      visa_send_form: T, visa_form_tracker: T, visa_bank_analyser: T, visa_intelligence: T,
      payments_view: T, payments_view_all: T, payments_create: T, payments_manage: T, payments_edit: T, payments_refund: T, payments_delete: F,
      accounting_view: T, accounting_export: T, invoices_view: T, invoices_create: T, invoices_send: T,
      payroll_view: T, payroll_run: F,
      reports_view: T, reports_submit: T, reports_all: T, reports_revenue: T, reports_staff: T, reports_export: T,
      staff_view: T, staff_create: F, staff_edit: T, staff_delete: F, staff_manage_roles: F,
      applications_view: T, applications_view_all: T, applications_create: T, applications_edit: T, applications_delete: F, applications_assign: T, applications_approve: T,
      inbox_view: T, inbox_reply: T, inbox_assign: T, inbox_delete: F,
      notifications_view: T, notifications_send: T, notifications_broadcast: T,
      destinations_view: T, destinations_edit: T, hotel_promos_view: T, hotel_promos_edit: T, flight_extras_view: T, jade_miles_view: T,
      cms_view: T, cms_edit: T, cms_publish: T,
      roles_view: T, roles_manage: F, roles_assign: F,
      settings_view: T, settings_edit: F, settings_roles: F, settings_integrations: F,
    },
  },
  {
    role:  'senior_manager',
    label: 'Senior Manager',
    color: '#C9A84C',
    permissions: {
      dashboard_view: T, dashboard_stats_all: F,
      clients_view: T, clients_create: T, clients_edit: T, clients_delete: F,
      leads_view: T, leads_manage: T,
      bookings_view: T, bookings_view_all: T, bookings_create: T, bookings_edit: T, bookings_cancel: F, bookings_delete: F,
      flights_search: T, flight_deals_view: T, ticket_generator: T, itinerary_planner: T, transfers_view: T,
      trips_view: T, trips_view_all: T, trips_create: T, trips_edit: T, trips_delete: F, trips_assign: T, trips_proposals: T,
      visa_view: T, visa_view_all: T, visa_own: T, visa_create: T, visa_edit: T, visa_approve: T, visa_delete: F,
      visa_send_form: T, visa_form_tracker: T, visa_bank_analyser: T, visa_intelligence: T,
      payments_view: T, payments_view_all: F, payments_create: F, payments_manage: F, payments_edit: F, payments_refund: F, payments_delete: F,
      accounting_view: F, accounting_export: F, invoices_view: F, invoices_create: F, invoices_send: F,
      payroll_view: F, payroll_run: F,
      reports_view: T, reports_submit: T, reports_all: F, reports_revenue: F, reports_staff: F, reports_export: T,
      staff_view: T, staff_create: F, staff_edit: F, staff_delete: F, staff_manage_roles: F,
      applications_view: T, applications_view_all: T, applications_create: T, applications_edit: T, applications_delete: F, applications_assign: T, applications_approve: T,
      inbox_view: T, inbox_reply: T, inbox_assign: T, inbox_delete: F,
      notifications_view: T, notifications_send: T, notifications_broadcast: F,
      destinations_view: T, destinations_edit: F, hotel_promos_view: T, hotel_promos_edit: F, flight_extras_view: T, jade_miles_view: T,
      cms_view: T, cms_edit: T, cms_publish: F,
      roles_view: F, roles_manage: F, roles_assign: F,
      settings_view: F, settings_edit: F, settings_roles: F, settings_integrations: F,
    },
  },
  {
    role:  'visa_officer',
    label: 'Visa Officer',
    color: '#7C3AED',
    permissions: {
      dashboard_view: T, dashboard_stats_all: F,
      clients_view: T, clients_create: T, clients_edit: T, clients_delete: F,
      leads_view: T, leads_manage: F,
      bookings_view: F, bookings_view_all: F, bookings_create: F, bookings_edit: F, bookings_cancel: F, bookings_delete: F,
      flights_search: F, flight_deals_view: F, ticket_generator: F, itinerary_planner: F, transfers_view: F,
      trips_view: F, trips_view_all: F, trips_create: F, trips_edit: F, trips_delete: F, trips_assign: F, trips_proposals: F,
      visa_view: T, visa_view_all: T, visa_own: T, visa_create: T, visa_edit: T, visa_approve: T, visa_delete: F,
      visa_send_form: T, visa_form_tracker: T, visa_bank_analyser: T, visa_intelligence: T,
      payments_view: F, payments_view_all: F, payments_create: F, payments_manage: F, payments_edit: F, payments_refund: F, payments_delete: F,
      accounting_view: F, accounting_export: F, invoices_view: F, invoices_create: F, invoices_send: F,
      payroll_view: F, payroll_run: F,
      reports_view: T, reports_submit: T, reports_all: F, reports_revenue: F, reports_staff: F, reports_export: F,
      staff_view: F, staff_create: F, staff_edit: F, staff_delete: F, staff_manage_roles: F,
      applications_view: T, applications_view_all: T, applications_create: T, applications_edit: T, applications_delete: F, applications_assign: F, applications_approve: T,
      inbox_view: T, inbox_reply: T, inbox_assign: F, inbox_delete: F,
      notifications_view: T, notifications_send: F, notifications_broadcast: F,
      destinations_view: F, destinations_edit: F, hotel_promos_view: F, hotel_promos_edit: F, flight_extras_view: F, jade_miles_view: F,
      cms_view: F, cms_edit: F, cms_publish: F,
      roles_view: F, roles_manage: F, roles_assign: F,
      settings_view: F, settings_edit: F, settings_roles: F, settings_integrations: F,
    },
  },
  {
    role:  'coordinator',
    label: 'Coordinator',
    color: '#2563EB',
    permissions: {
      dashboard_view: T, dashboard_stats_all: F,
      clients_view: T, clients_create: T, clients_edit: T, clients_delete: F,
      leads_view: T, leads_manage: F,
      bookings_view: T, bookings_view_all: F, bookings_create: T, bookings_edit: T, bookings_cancel: F, bookings_delete: F,
      flights_search: T, flight_deals_view: T, ticket_generator: T, itinerary_planner: T, transfers_view: T,
      trips_view: T, trips_view_all: F, trips_create: T, trips_edit: T, trips_delete: F, trips_assign: F, trips_proposals: T,
      visa_view: T, visa_view_all: F, visa_own: T, visa_create: T, visa_edit: T, visa_approve: F, visa_delete: F,
      visa_send_form: T, visa_form_tracker: T, visa_bank_analyser: T, visa_intelligence: T,
      payments_view: T, payments_view_all: F, payments_create: F, payments_manage: F, payments_edit: F, payments_refund: F, payments_delete: F,
      accounting_view: F, accounting_export: F, invoices_view: F, invoices_create: F, invoices_send: F,
      payroll_view: F, payroll_run: F,
      reports_view: T, reports_submit: T, reports_all: F, reports_revenue: F, reports_staff: F, reports_export: F,
      staff_view: F, staff_create: F, staff_edit: F, staff_delete: F, staff_manage_roles: F,
      applications_view: T, applications_view_all: F, applications_create: T, applications_edit: T, applications_delete: F, applications_assign: F, applications_approve: F,
      inbox_view: T, inbox_reply: T, inbox_assign: F, inbox_delete: F,
      notifications_view: T, notifications_send: F, notifications_broadcast: F,
      destinations_view: F, destinations_edit: F, hotel_promos_view: F, hotel_promos_edit: F, flight_extras_view: F, jade_miles_view: F,
      cms_view: F, cms_edit: F, cms_publish: F,
      roles_view: F, roles_manage: F, roles_assign: F,
      settings_view: F, settings_edit: F, settings_roles: F, settings_integrations: F,
    },
  },
  {
    role:  'flight_staff',
    label: 'Flight Ticketing Staff',
    color: '#0EA5E9',
    permissions: {
      dashboard_view: T, dashboard_stats_all: F,
      clients_view: T, clients_create: T, clients_edit: T, clients_delete: F,
      leads_view: T, leads_manage: F,
      bookings_view: T, bookings_view_all: F, bookings_create: T, bookings_edit: T, bookings_cancel: F, bookings_delete: F,
      flights_search: T, flight_deals_view: T, ticket_generator: T, itinerary_planner: T, transfers_view: T,
      trips_view: T, trips_view_all: F, trips_create: T, trips_edit: T, trips_delete: F, trips_assign: F, trips_proposals: T,
      visa_view: F, visa_view_all: F, visa_own: F, visa_create: F, visa_edit: F, visa_approve: F, visa_delete: F,
      visa_send_form: F, visa_form_tracker: F, visa_bank_analyser: F, visa_intelligence: F,
      payments_view: T, payments_view_all: F, payments_create: F, payments_manage: F, payments_edit: F, payments_refund: F, payments_delete: F,
      accounting_view: F, accounting_export: F, invoices_view: F, invoices_create: F, invoices_send: F,
      payroll_view: F, payroll_run: F,
      reports_view: T, reports_submit: T, reports_all: F, reports_revenue: F, reports_staff: F, reports_export: F,
      staff_view: F, staff_create: F, staff_edit: F, staff_delete: F, staff_manage_roles: F,
      applications_view: T, applications_view_all: F, applications_create: T, applications_edit: T, applications_delete: F, applications_assign: F, applications_approve: F,
      inbox_view: T, inbox_reply: T, inbox_assign: F, inbox_delete: F,
      notifications_view: T, notifications_send: F, notifications_broadcast: F,
      destinations_view: F, destinations_edit: F, hotel_promos_view: F, hotel_promos_edit: F, flight_extras_view: T, jade_miles_view: F,
      cms_view: F, cms_edit: F, cms_publish: F,
      roles_view: F, roles_manage: F, roles_assign: F,
      settings_view: F, settings_edit: F, settings_roles: F, settings_integrations: F,
    },
  },
  {
    role:  'tours_staff',
    label: 'Tours & Activities Staff',
    color: '#16A34A',
    permissions: {
      dashboard_view: T, dashboard_stats_all: F,
      clients_view: T, clients_create: T, clients_edit: T, clients_delete: F,
      leads_view: T, leads_manage: F,
      bookings_view: T, bookings_view_all: F, bookings_create: T, bookings_edit: T, bookings_cancel: F, bookings_delete: F,
      flights_search: F, flight_deals_view: F, ticket_generator: F, itinerary_planner: T, transfers_view: T,
      trips_view: T, trips_view_all: F, trips_create: T, trips_edit: T, trips_delete: F, trips_assign: F, trips_proposals: T,
      visa_view: F, visa_view_all: F, visa_own: F, visa_create: F, visa_edit: F, visa_approve: F, visa_delete: F,
      visa_send_form: F, visa_form_tracker: F, visa_bank_analyser: F, visa_intelligence: F,
      payments_view: T, payments_view_all: F, payments_create: F, payments_manage: F, payments_edit: F, payments_refund: F, payments_delete: F,
      accounting_view: F, accounting_export: F, invoices_view: F, invoices_create: F, invoices_send: F,
      payroll_view: F, payroll_run: F,
      reports_view: T, reports_submit: T, reports_all: F, reports_revenue: F, reports_staff: F, reports_export: F,
      staff_view: F, staff_create: F, staff_edit: F, staff_delete: F, staff_manage_roles: F,
      applications_view: T, applications_view_all: F, applications_create: T, applications_edit: T, applications_delete: F, applications_assign: F, applications_approve: F,
      inbox_view: T, inbox_reply: T, inbox_assign: F, inbox_delete: F,
      notifications_view: T, notifications_send: F, notifications_broadcast: F,
      destinations_view: T, destinations_edit: F, hotel_promos_view: T, hotel_promos_edit: F, flight_extras_view: F, jade_miles_view: F,
      cms_view: F, cms_edit: F, cms_publish: F,
      roles_view: F, roles_manage: F, roles_assign: F,
      settings_view: F, settings_edit: F, settings_roles: F, settings_integrations: F,
    },
  },
  {
    role:  'hotel_staff',
    label: 'Hotel Reservation Staff',
    color: '#06B6D4',
    permissions: {
      dashboard_view: T, dashboard_stats_all: F,
      clients_view: T, clients_create: T, clients_edit: T, clients_delete: F,
      leads_view: T, leads_manage: F,
      bookings_view: T, bookings_view_all: F, bookings_create: T, bookings_edit: T, bookings_cancel: F, bookings_delete: F,
      flights_search: F, flight_deals_view: F, ticket_generator: F, itinerary_planner: T, transfers_view: T,
      trips_view: T, trips_view_all: F, trips_create: T, trips_edit: T, trips_delete: F, trips_assign: F, trips_proposals: T,
      visa_view: F, visa_view_all: F, visa_own: F, visa_create: F, visa_edit: F, visa_approve: F, visa_delete: F,
      visa_send_form: F, visa_form_tracker: F, visa_bank_analyser: F, visa_intelligence: F,
      payments_view: T, payments_view_all: F, payments_create: F, payments_manage: F, payments_edit: F, payments_refund: F, payments_delete: F,
      accounting_view: F, accounting_export: F, invoices_view: F, invoices_create: F, invoices_send: F,
      payroll_view: F, payroll_run: F,
      reports_view: T, reports_submit: T, reports_all: F, reports_revenue: F, reports_staff: F, reports_export: F,
      staff_view: F, staff_create: F, staff_edit: F, staff_delete: F, staff_manage_roles: F,
      applications_view: T, applications_view_all: F, applications_create: T, applications_edit: T, applications_delete: F, applications_assign: F, applications_approve: F,
      inbox_view: T, inbox_reply: T, inbox_assign: F, inbox_delete: F,
      notifications_view: T, notifications_send: F, notifications_broadcast: F,
      destinations_view: T, destinations_edit: F, hotel_promos_view: T, hotel_promos_edit: T, flight_extras_view: F, jade_miles_view: F,
      cms_view: F, cms_edit: F, cms_publish: F,
      roles_view: F, roles_manage: F, roles_assign: F,
      settings_view: F, settings_edit: F, settings_roles: F, settings_integrations: F,
    },
  },
  {
    role:  'sales_agent',
    label: 'Sales Agent',
    color: '#EA580C',
    permissions: {
      dashboard_view: T, dashboard_stats_all: F,
      clients_view: T, clients_create: T, clients_edit: T, clients_delete: F,
      leads_view: T, leads_manage: T,
      bookings_view: T, bookings_view_all: F, bookings_create: T, bookings_edit: F, bookings_cancel: F, bookings_delete: F,
      flights_search: T, flight_deals_view: T, ticket_generator: F, itinerary_planner: F, transfers_view: F,
      trips_view: T, trips_view_all: F, trips_create: T, trips_edit: F, trips_delete: F, trips_assign: F, trips_proposals: T,
      visa_view: T, visa_view_all: F, visa_own: T, visa_create: T, visa_edit: F, visa_approve: F, visa_delete: F,
      visa_send_form: F, visa_form_tracker: F, visa_bank_analyser: F, visa_intelligence: F,
      payments_view: T, payments_view_all: F, payments_create: F, payments_manage: F, payments_edit: F, payments_refund: F, payments_delete: F,
      accounting_view: F, accounting_export: F, invoices_view: F, invoices_create: F, invoices_send: F,
      payroll_view: F, payroll_run: F,
      reports_view: T, reports_submit: T, reports_all: F, reports_revenue: F, reports_staff: F, reports_export: F,
      staff_view: F, staff_create: F, staff_edit: F, staff_delete: F, staff_manage_roles: F,
      applications_view: T, applications_view_all: F, applications_create: T, applications_edit: T, applications_delete: F, applications_assign: F, applications_approve: F,
      inbox_view: T, inbox_reply: T, inbox_assign: F, inbox_delete: F,
      notifications_view: T, notifications_send: F, notifications_broadcast: F,
      destinations_view: T, destinations_edit: F, hotel_promos_view: T, hotel_promos_edit: F, flight_extras_view: T, jade_miles_view: T,
      cms_view: F, cms_edit: F, cms_publish: F,
      roles_view: F, roles_manage: F, roles_assign: F,
      settings_view: F, settings_edit: F, settings_roles: F, settings_integrations: F,
    },
  },
  {
    role:  'accountant',
    label: 'Accountant',
    color: '#E11D48',
    permissions: {
      dashboard_view: T, dashboard_stats_all: T,
      clients_view: T, clients_create: F, clients_edit: F, clients_delete: F,
      leads_view: F, leads_manage: F,
      bookings_view: T, bookings_view_all: T, bookings_create: F, bookings_edit: F, bookings_cancel: F, bookings_delete: F,
      flights_search: F, flight_deals_view: F, ticket_generator: F, itinerary_planner: F, transfers_view: F,
      trips_view: F, trips_view_all: F, trips_create: F, trips_edit: F, trips_delete: F, trips_assign: F, trips_proposals: F,
      visa_view: F, visa_view_all: F, visa_own: F, visa_create: F, visa_edit: F, visa_approve: F, visa_delete: F,
      visa_send_form: F, visa_form_tracker: F, visa_bank_analyser: F, visa_intelligence: F,
      payments_view: T, payments_view_all: T, payments_create: T, payments_manage: T, payments_edit: T, payments_refund: T, payments_delete: F,
      accounting_view: T, accounting_export: T, invoices_view: T, invoices_create: T, invoices_send: T,
      payroll_view: T, payroll_run: T,
      reports_view: T, reports_submit: T, reports_all: T, reports_revenue: T, reports_staff: T, reports_export: T,
      staff_view: T, staff_create: F, staff_edit: F, staff_delete: F, staff_manage_roles: F,
      applications_view: T, applications_view_all: T, applications_create: F, applications_edit: F, applications_delete: F, applications_assign: F, applications_approve: F,
      inbox_view: T, inbox_reply: F, inbox_assign: F, inbox_delete: F,
      notifications_view: T, notifications_send: F, notifications_broadcast: F,
      destinations_view: F, destinations_edit: F, hotel_promos_view: F, hotel_promos_edit: F, flight_extras_view: F, jade_miles_view: F,
      cms_view: F, cms_edit: F, cms_publish: F,
      roles_view: F, roles_manage: F, roles_assign: F,
      settings_view: F, settings_edit: F, settings_roles: F, settings_integrations: F,
    },
  },
  {
    role:  'customer_support',
    label: 'Customer Support',
    color: '#64748B',
    permissions: {
      dashboard_view: T, dashboard_stats_all: F,
      clients_view: T, clients_create: T, clients_edit: T, clients_delete: F,
      leads_view: T, leads_manage: F,
      bookings_view: T, bookings_view_all: F, bookings_create: F, bookings_edit: F, bookings_cancel: F, bookings_delete: F,
      flights_search: F, flight_deals_view: T, ticket_generator: F, itinerary_planner: F, transfers_view: F,
      trips_view: T, trips_view_all: F, trips_create: F, trips_edit: F, trips_delete: F, trips_assign: F, trips_proposals: F,
      visa_view: T, visa_view_all: F, visa_own: T, visa_create: F, visa_edit: F, visa_approve: F, visa_delete: F,
      visa_send_form: F, visa_form_tracker: T, visa_bank_analyser: F, visa_intelligence: F,
      payments_view: T, payments_view_all: F, payments_create: F, payments_manage: F, payments_edit: F, payments_refund: F, payments_delete: F,
      accounting_view: F, accounting_export: F, invoices_view: F, invoices_create: F, invoices_send: F,
      payroll_view: F, payroll_run: F,
      reports_view: T, reports_submit: T, reports_all: F, reports_revenue: F, reports_staff: F, reports_export: F,
      staff_view: F, staff_create: F, staff_edit: F, staff_delete: F, staff_manage_roles: F,
      applications_view: T, applications_view_all: F, applications_create: T, applications_edit: T, applications_delete: F, applications_assign: F, applications_approve: F,
      inbox_view: T, inbox_reply: T, inbox_assign: F, inbox_delete: F,
      notifications_view: T, notifications_send: F, notifications_broadcast: F,
      destinations_view: T, destinations_edit: F, hotel_promos_view: T, hotel_promos_edit: F, flight_extras_view: T, jade_miles_view: T,
      cms_view: F, cms_edit: F, cms_publish: F,
      roles_view: F, roles_manage: F, roles_assign: F,
      settings_view: F, settings_edit: F, settings_roles: F, settings_integrations: F,
    },
  },
  {
    role:  'sales_rep',
    label: 'Sales Representative',
    color: '#16A34A',
    permissions: {
      dashboard_view: T, dashboard_stats_all: F,
      clients_view: T, clients_create: T, clients_edit: T, clients_delete: F,
      leads_view: T, leads_manage: T,
      bookings_view: T, bookings_view_all: F, bookings_create: T, bookings_edit: F, bookings_cancel: F, bookings_delete: F,
      flights_search: T, flight_deals_view: T, ticket_generator: F, itinerary_planner: F, transfers_view: F,
      trips_view: T, trips_view_all: F, trips_create: T, trips_edit: T, trips_delete: F, trips_assign: F, trips_proposals: F,
      visa_view: T, visa_view_all: F, visa_own: T, visa_create: T, visa_edit: T, visa_delete: F, visa_approve: F,
      visa_send_form: F, visa_form_tracker: F, visa_bank_analyser: F, visa_intelligence: F,
      payments_view: T, payments_view_all: F, payments_create: F, payments_manage: F, payments_edit: F, payments_refund: F, payments_delete: F,
      accounting_view: F, accounting_export: F, invoices_view: F, invoices_create: F, invoices_send: F,
      payroll_view: F, payroll_run: F,
      reports_view: F, reports_submit: F, reports_all: F, reports_revenue: F, reports_staff: F, reports_export: F,
      staff_view: F, staff_create: F, staff_edit: F, staff_delete: F, staff_manage_roles: F,
      applications_view: T, applications_view_all: F, applications_create: T, applications_edit: T, applications_delete: F, applications_assign: F, applications_approve: F,
      inbox_view: T, inbox_reply: T, inbox_assign: F, inbox_delete: F,
      notifications_view: T, notifications_send: F, notifications_broadcast: F,
      destinations_view: T, destinations_edit: F, hotel_promos_view: T, hotel_promos_edit: F, flight_extras_view: T, jade_miles_view: T,
      cms_view: F, cms_edit: F, cms_publish: F,
      roles_view: F, roles_manage: F, roles_assign: F,
      settings_view: F, settings_edit: F, settings_roles: F, settings_integrations: F,
    },
  },
]

async function main() {
  console.log('🌱 Seeding role permissions…')

  for (const rp of ROLE_PERMISSIONS) {
    await prisma.rolePermission.upsert({
      where:  { role: rp.role },
      update: { label: rp.label, color: rp.color, permissions: rp.permissions },
      create: rp,
    })
    console.log(`  ✅ ${rp.label} (${rp.role})`)
  }

  console.log('\n✨ Role permissions seeded successfully.')
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
