// Static seed data — used when DB is empty or as fallback
// These match the featured cards on the activities page
export const STATIC_ACTIVITIES = [
  {
    slug:         'serengeti-safari-3-day',
    title:        'Serengeti Safari — 3 Days',
    shortDesc:    'Witness the Great Migration. Stay in a luxury tented camp under infinite stars.',
    description:  'The Serengeti is one of the most iconic wildlife destinations on earth. Over three days, you will traverse golden savannas, witness vast herds of wildebeest and zebra, and track the Big Five with expert Tanzanian guides. Nights are spent in a luxury tented camp deep inside the park — candlelit dinners, starlit skies, and the distant sound of lions are your backdrop. This is not a tour. This is an encounter with the wild that will stay with you forever.',
    image:        'https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=1200&q=90',
    price:        890,
    currency:     'USD',
    duration:     '3 days · 2 nights',
    location:     'Tanzania',
    category:     'wildlife',
    badge:        'Bestseller',
    meetingPoint: 'Kilimanjaro International Airport (JRO) or Arusha Town Centre',
    included:     [
      'Luxury tented camp accommodation (2 nights)',
      'All meals and non-alcoholic drinks',
      'Expert English-speaking safari guide',
      'Game drives in 4×4 safari vehicle',
      'Park entrance fees',
      'Airport/hotel transfers',
    ],
    notIncluded:  ['International flights', 'Travel insurance', 'Alcoholic drinks', 'Tips and gratuities'],
    notes:        'Best time to visit: June–October for dry season and Great Migration. Yellow fever vaccination may be required.',
    isFeatured:   true,
    isPublished:  true,
  },
  {
    slug:         'dubai-desert-sunset-experience',
    title:        'Dubai Desert Sunset Experience',
    shortDesc:    'Dune bashing, camel riding, and a traditional Bedouin dinner under the stars.',
    description:  'Leave the city behind and venture deep into the Arabian desert for an evening you will never forget. Your expert driver will take you dune bashing through the golden sands as the sun begins to set. Arrive at a traditional Bedouin camp for camel riding, sandboarding, henna painting, and shisha before sitting down to a sumptuous Middle Eastern feast under a canopy of stars. Belly dancing and tanoura shows complete a truly magical evening.',
    image:        'https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=1200&q=90',
    price:        350,
    currency:     'AED',
    duration:     '6 hours',
    location:     'Dubai, UAE',
    category:     'adventure',
    badge:        'Top Rated',
    meetingPoint: 'Hotel pickup available across Dubai and Sharjah',
    included:     [
      'Hotel pickup and drop-off',
      'Dune bashing in 4×4 vehicle',
      'Camel riding',
      'Sandboarding',
      'Henna painting',
      'BBQ dinner with vegetarian options',
      'Unlimited soft drinks, tea, and coffee',
      'Belly dancing and tanoura show',
    ],
    notIncluded:  ['Alcoholic drinks', 'Quad biking (available on-site for extra cost)'],
    notes:        'Pickup times are usually between 3–4pm. Not recommended for pregnant women or people with back problems.',
    isFeatured:   true,
    isPublished:  true,
  },
  {
    slug:         'zanzibar-spice-culture-tour',
    title:        'Zanzibar Spice & Culture Tour',
    shortDesc:    'Stone Town walking tour, spice farm visit, and sunset dhow cruise included.',
    description:  'Zanzibar is known as the Spice Island, and this full-day tour brings its rich history and flavours to life. You will begin with a walking tour of Stone Town — a UNESCO World Heritage Site — exploring ancient Arab trading houses, colonial-era churches, and vibrant local markets. After lunch, visit a working spice farm where you can see, touch, and taste nutmeg, cloves, vanilla, and cinnamon growing in their natural environment. The day concludes with a traditional wooden dhow sunset cruise along the coast, with snacks and drinks included.',
    image:        'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1200&q=90',
    price:        55,
    currency:     'USD',
    duration:     '8 hours',
    location:     'Zanzibar, Tanzania',
    category:     'culture',
    badge:        'Walz Pick',
    meetingPoint: 'Your hotel in Stone Town or Zanzibar Town',
    included:     [
      'Certified English-speaking guide',
      'Stone Town walking tour',
      'Spice farm entrance and tour',
      'Lunch at local restaurant',
      'Sunset dhow cruise',
      'Snacks and soft drinks on the boat',
    ],
    notIncluded:  ['Hotel pickup outside Stone Town area', 'Tips', 'Personal purchases at the spice farm'],
    notes:        'Modest dress recommended for Stone Town (shoulders and knees covered). Bring sunscreen for the dhow cruise.',
    isFeatured:   true,
    isPublished:  true,
  },
  {
    slug:         'london-thames-sunset-private-boat',
    title:        'London Thames at Sunset — Private Boat',
    shortDesc:    "A champagne cruise past Tower Bridge, Big Ben, and the City skyline.",
    description:  "Experience London the way most visitors never do — from the water at golden hour. This exclusive private charter takes you along the Thames as the sun sets behind the London skyline. You will drift past the Tower of London, Tower Bridge, St Paul's Cathedral, the Houses of Parliament, and the Tate Modern with a glass of champagne in hand. Your private captain provides running commentary on every landmark while you and your group enjoy the ultimate city view. Available for couples, families, and small groups up to 12.",
    image:        'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=1200&q=90',
    price:        120,
    currency:     'GBP',
    duration:     '2 hours',
    location:     'London, United Kingdom',
    category:     'beach',
    badge:        'Private',
    meetingPoint: 'Tower Millennium Pier, London EC3N 4AF',
    included:     [
      'Private boat charter (up to 12 guests)',
      'Welcome champagne or sparkling water',
      'Experienced private captain',
      'Commentary on all major landmarks',
      'Complimentary snacks',
    ],
    notIncluded:  ['Additional food and drinks', 'Gratuities for captain'],
    notes:        'Departure times available from 4pm–8pm. Sunset times vary by season. Minimum 2 guests required.',
    isFeatured:   true,
    isPublished:  true,
  },
]

export function getActivityBySlug(slug: string) {
  return STATIC_ACTIVITIES.find(a => a.slug === slug) ?? null
}
