/**
 * Visa Intelligence Hub seed script
 * Run: DATABASE_URL="..." npx ts-node --compiler-options '{"module":"CommonJS"}' scripts/seed-visa-data.ts
 */

import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('🌍 Seeding Visa Intelligence Hub data...')

  // ── Country Portals ──────────────────────────────────────────────────────────
  const portals = [
    {
      destinationIso2: 'GB',
      countryName: 'United Kingdom',
      flagEmoji: '🇬🇧',
      region: 'Europe',
      portalUrl: 'https://www.gov.uk/apply-uk-visa',
      walzFeeUsd: 188, walzFeeNgn: 300000,
      govtFeeUsd: 145, govtFeeAmount: 115, govtFeeCurrency: 'GBP',
      processingDaysMin: 15, processingDaysMax: 21,
      maxStayDays: 180, validityDays: 180, singleOrMultiple: 'multiple',
      requiredDocuments: [
        'Valid passport — minimum 6 months validity',
        '2 passport photographs (white background)',
        '6-month bank statement — minimum NGN 3M balance',
        'Employment letter stating salary and leave dates',
        'Approved leave letter with specific dates',
        'Travel itinerary',
        'Hotel booking confirmation',
        'Return flight booking (refundable only)',
        'Proof of ties to Nigeria (property, family, job)',
      ],
      jadeTips: 'Your bank statement is the most important document. It must show consistent activity over 6 months with a minimum balance of NGN 3 million. Avoid large lump sum deposits just before applying — officers notice this immediately.',
      commonRefusals: [
        'Insufficient bank balance',
        'Lump sum deposit just before applying',
        'Missing approved leave dates',
        'No ties to home country demonstrated',
        'Incomplete travel itinerary',
        'Non-refundable flight booking submitted',
      ],
      advisoryLevel: 1,
    },
    {
      destinationIso2: 'CA',
      countryName: 'Canada',
      flagEmoji: '🇨🇦',
      region: 'Americas',
      portalUrl: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada.html',
      walzFeeUsd: 281, walzFeeNgn: 450000,
      govtFeeUsd: 140, govtFeeAmount: 185, govtFeeCurrency: 'CAD',
      processingDaysMin: 45, processingDaysMax: 84,
      maxStayDays: 180, validityDays: 3650, singleOrMultiple: 'multiple',
      requiredDocuments: [
        'Valid passport — minimum 6 months validity',
        '2 passport photographs',
        '6-month bank statement — minimum NGN 6.5M',
        'Employment letter confirming position and salary',
        'Approved leave letter with specific dates',
        'CAC documents (if self-employed)',
        'Marriage certificate (if applicable)',
        'Property documents to demonstrate ties to Nigeria',
        'Biometrics at VFS Global Lagos or Abuja',
      ],
      jadeTips: 'Canada has a 55% approval rate for Nigerian applicants. The key is demonstrating strong ties to Nigeria — property ownership, family at home, and a stable job all help significantly. A previous US or UK visa also strengthens your application considerably.',
      commonRefusals: [
        'Insufficient proof of ties to Nigeria',
        'Bank balance below recommended minimum',
        'Inconsistent employment documentation',
        'No previous travel history to strengthen application',
        'Biometrics not completed before submission',
      ],
      advisoryLevel: 1,
    },
    {
      destinationIso2: 'AE',
      countryName: 'United Arab Emirates',
      flagEmoji: '🇦🇪',
      region: 'Middle East',
      portalUrl: 'https://smartservices.icp.gov.ae',
      walzFeeUsd: 470, walzFeeNgn: 750000,
      govtFeeUsd: 0, govtFeeAmount: 0, govtFeeCurrency: 'USD',
      processingDaysMin: 3, processingDaysMax: 5,
      maxStayDays: 30, validityDays: 30, singleOrMultiple: 'single',
      requiredDocuments: [
        'Valid passport — minimum 6 months validity',
        'Passport photograph (white background)',
        '3-month bank statement',
        'Employment letter',
        'Return flight booking',
        'Hotel booking confirmation',
      ],
      jadeTips: 'UAE visa is our fastest processing — typically 3 to 5 days. Government fee is included in our service fee so there are no surprise costs. Perfect for business trips and holidays. Approval rates are excellent for our clients.',
      commonRefusals: [
        'Previous visa overstay in UAE or GCC countries',
        'Insufficient bank balance',
        'Missing return flight confirmation',
      ],
      advisoryLevel: 1,
    },
    {
      destinationIso2: 'FR',
      countryName: 'Schengen Europe',
      flagEmoji: '🇪🇺',
      region: 'Europe',
      portalUrl: 'https://france-visas.gouv.fr',
      walzFeeUsd: 231, walzFeeNgn: 370000,
      govtFeeUsd: 90, govtFeeAmount: 80, govtFeeCurrency: 'EUR',
      processingDaysMin: 15, processingDaysMax: 21,
      maxStayDays: 90, validityDays: 180, singleOrMultiple: 'multiple',
      requiredDocuments: [
        'Valid passport — minimum 3 months beyond return date',
        '2 passport photographs (35x45mm white background)',
        'Travel insurance — minimum €30,000 coverage, entire Schengen area',
        '6-month bank statement',
        'Employment letter',
        'Hotel bookings for entire trip duration',
        'Return flight itinerary',
        'Cover letter explaining purpose of visit',
        'Proof of accommodation for every night',
      ],
      jadeTips: 'Apply through the embassy of the country where you will spend the most nights. Travel insurance is mandatory and must cover the entire Schengen area. The 90-day rule applies across all 26 Schengen countries combined — plan carefully.',
      commonRefusals: [
        'Travel insurance below €30,000 coverage',
        'Missing accommodation proof for some nights',
        'Inconsistent travel plans in cover letter',
        'Applying through wrong embassy',
        'Bank balance insufficient for trip duration',
      ],
      advisoryLevel: 1,
    },
    {
      destinationIso2: 'US',
      countryName: 'United States',
      flagEmoji: '🇺🇸',
      region: 'Americas',
      portalUrl: 'https://ceac.state.gov',
      walzFeeUsd: 344, walzFeeNgn: 550000,
      govtFeeUsd: 185, govtFeeAmount: 185, govtFeeCurrency: 'USD',
      processingDaysMin: 60, processingDaysMax: 120,
      maxStayDays: 180, validityDays: 3650, singleOrMultiple: 'multiple',
      requiredDocuments: [
        'Valid passport — minimum 6 months validity',
        'DS-160 form completed online',
        '6-month bank statement',
        'Employment letter',
        'Strong ties to Nigeria evidence',
        'Property documents',
        'Interview preparation (mandatory)',
        'Visa photo meeting US specifications',
      ],
      jadeTips: 'The US visa interview is the most important part. You must clearly demonstrate strong ties to Nigeria and a genuine reason to return. We prepare all our clients thoroughly for interview questions — our success rate is significantly above average.',
      commonRefusals: [
        'Failure to demonstrate strong ties to Nigeria',
        'Unconvincing interview answers',
        'Insufficient financial documentation',
        'Previous visa overstay anywhere',
        'Travel purpose not clearly explained',
      ],
      advisoryLevel: 1,
    },
    {
      destinationIso2: 'VN',
      countryName: 'Vietnam',
      flagEmoji: '🇻🇳',
      region: 'Asia',
      portalUrl: 'https://evisa.gov.vn',
      walzFeeUsd: 50, walzFeeNgn: 80000,
      govtFeeUsd: 25, govtFeeAmount: 25, govtFeeCurrency: 'USD',
      processingDaysMin: 3, processingDaysMax: 3,
      maxStayDays: 90, validityDays: 90, singleOrMultiple: 'single',
      requiredDocuments: [
        'Valid passport — minimum 6 months validity',
        'Passport photo (white background)',
        'Completed e-visa application',
        'Entry/exit dates',
        'Accommodation address in Vietnam',
      ],
      jadeTips: 'Vietnam e-visa is straightforward — apply online at evisa.gov.vn. Processing takes 3 business days. The e-visa allows 90 days stay and is single entry. For multiple entry, apply for a different visa category.',
      commonRefusals: ['Incorrect passport details on application', 'Entry point mismatch'],
      advisoryLevel: 1,
    },
    {
      destinationIso2: 'IN',
      countryName: 'India',
      flagEmoji: '🇮🇳',
      region: 'Asia',
      portalUrl: 'https://indianvisaonline.gov.in',
      walzFeeUsd: 75, walzFeeNgn: 120000,
      govtFeeUsd: 25, govtFeeAmount: 25, govtFeeCurrency: 'USD',
      processingDaysMin: 3, processingDaysMax: 5,
      maxStayDays: 60, validityDays: 60, singleOrMultiple: 'double',
      requiredDocuments: [
        'Valid passport — minimum 6 months validity',
        'Passport photograph',
        'Return flight booking',
        'Hotel booking confirmation',
        'Bank statement (3 months)',
        'Completed e-visa application form',
      ],
      jadeTips: 'India e-Tourist Visa (eTV) is available online. Apply at least 4 days before travel. The 60-day double entry is ideal for most visits. Business e-visa available for those attending conferences or meetings.',
      commonRefusals: ['Photo not meeting specifications', 'Missing accommodation details'],
      advisoryLevel: 1,
    },
    {
      destinationIso2: 'TR',
      countryName: 'Turkey',
      flagEmoji: '🇹🇷',
      region: 'Europe',
      portalUrl: 'https://evisa.gov.tr',
      walzFeeUsd: 75, walzFeeNgn: 120000,
      govtFeeUsd: 50, govtFeeAmount: 50, govtFeeCurrency: 'USD',
      processingDaysMin: 1, processingDaysMax: 1,
      maxStayDays: 90, validityDays: 90, singleOrMultiple: 'single',
      requiredDocuments: [
        'Valid passport — minimum 6 months validity',
        'Credit/debit card for payment',
        'Email address for visa delivery',
        'Hotel booking confirmation',
        'Return flight booking',
      ],
      jadeTips: 'Turkey e-visa is one of the easiest — apply at evisa.gov.tr, pay online, and receive your visa by email within minutes. Nigerian passport holders are eligible. Perfect gateway for Europe exploration.',
      commonRefusals: ['Invalid passport details', 'Payment failure'],
      advisoryLevel: 2,
    },
    {
      destinationIso2: 'KE',
      countryName: 'Kenya',
      flagEmoji: '🇰🇪',
      region: 'Africa',
      portalUrl: 'https://etakenya.go.ke',
      walzFeeUsd: 50, walzFeeNgn: 80000,
      govtFeeUsd: 34, govtFeeAmount: 34, govtFeeCurrency: 'USD',
      processingDaysMin: 1, processingDaysMax: 3,
      maxStayDays: 90, validityDays: 90, singleOrMultiple: 'single',
      requiredDocuments: [
        'Valid passport — minimum 6 months validity',
        'Passport photograph',
        'Return flight booking',
        'Hotel booking confirmation',
        'Yellow fever vaccination certificate',
      ],
      jadeTips: 'Kenya eTA is fast and affordable. Yellow fever vaccination certificate is mandatory for Nigerian travellers. Apply at etakenya.go.ke at least 3 days before departure.',
      commonRefusals: ['Missing yellow fever certificate', 'Insufficient return flight proof'],
      advisoryLevel: 2,
    },
    {
      destinationIso2: 'EG',
      countryName: 'Egypt',
      flagEmoji: '🇪🇬',
      region: 'Africa',
      portalUrl: 'https://visa2egypt.gov.eg',
      walzFeeUsd: 50, walzFeeNgn: 80000,
      govtFeeUsd: 25, govtFeeAmount: 25, govtFeeCurrency: 'USD',
      processingDaysMin: 3, processingDaysMax: 5,
      maxStayDays: 30, validityDays: 30, singleOrMultiple: 'single',
      requiredDocuments: [
        'Valid passport — minimum 6 months validity',
        'Passport photograph',
        'Completed online application',
        'Return flight booking',
        'Hotel confirmation',
      ],
      jadeTips: 'Egypt e-visa is available at visa2egypt.gov.eg. Process takes 3-5 business days. The Sinai-only visa (on arrival) is cheaper if visiting only that region, but the e-visa gives full Egypt access.',
      commonRefusals: ['Inconsistent personal details', 'Missing accommodation confirmation'],
      advisoryLevel: 2,
    },
    {
      destinationIso2: 'PH',
      countryName: 'Philippines',
      flagEmoji: '🇵🇭',
      region: 'Asia',
      portalUrl: 'https://evisa.gov.ph',
      walzFeeUsd: 0, walzFeeNgn: 550000,
      govtFeeUsd: 0, govtFeeAmount: 0, govtFeeCurrency: 'USD',
      processingDaysMin: 14, processingDaysMax: 21,
      maxStayDays: 30, validityDays: 30, singleOrMultiple: 'single',
      requiredDocuments: [
        'Valid passport — minimum 6 months validity',
        'Passport photographs',
        '3-month bank statement',
        'Employment letter',
        'Return flight booking',
        'Hotel confirmation',
        'Tour itinerary (recommended)',
      ],
      jadeTips: 'Philippines visa for Nigerians requires embassy appointment in Abuja or Lagos. Allow 3-4 weeks for processing. Book early especially for holiday periods.',
      commonRefusals: ['Insufficient bank balance', 'Missing return flight evidence'],
      advisoryLevel: 1,
    },
    {
      destinationIso2: 'MA',
      countryName: 'Morocco',
      flagEmoji: '🇲🇦',
      region: 'Africa',
      portalUrl: 'https://portail.marocvis.net',
      walzFeeUsd: 369, walzFeeNgn: 590000,
      govtFeeUsd: 0, govtFeeAmount: 0, govtFeeCurrency: 'USD',
      processingDaysMin: 5, processingDaysMax: 7,
      maxStayDays: 90, validityDays: 90, singleOrMultiple: 'single',
      requiredDocuments: [
        'Valid passport — minimum 6 months validity',
        '2 passport photographs',
        '3-month bank statement',
        'Employment letter',
        'Hotel confirmation',
        'Return flight itinerary',
        'Travel insurance',
      ],
      jadeTips: 'Morocco visa for Nigerians is processed through the Moroccan consulate. Online appointment required. The country has become increasingly popular — apply early in peak season.',
      commonRefusals: ['Insufficient financial proof', 'No accommodation confirmation'],
      advisoryLevel: 1,
    },
    {
      destinationIso2: 'AU',
      countryName: 'Australia',
      flagEmoji: '🇦🇺',
      region: 'Oceania',
      portalUrl: 'https://immi.homeaffairs.gov.au',
      walzFeeUsd: 300, walzFeeNgn: 480000,
      govtFeeUsd: 145, govtFeeAmount: 145, govtFeeCurrency: 'USD',
      processingDaysMin: 30, processingDaysMax: 60,
      maxStayDays: 90, validityDays: 365, singleOrMultiple: 'multiple',
      requiredDocuments: [
        'Valid passport — minimum 6 months validity',
        'Passport photographs',
        '6-month bank statement',
        'Employment letter',
        'Evidence of accommodation',
        'Return flight booking',
        'Travel insurance (recommended)',
        'Invitation letter if visiting family/friends',
      ],
      jadeTips: 'Australia visa has a 3-6 month processing window. Apply well in advance. Demonstrating strong financial standing and ties to Nigeria is essential. Health examination may be required.',
      commonRefusals: ['Insufficient funds evidence', 'Previous visa overstay in any country', 'Health examination not completed'],
      advisoryLevel: 1,
    },
    {
      destinationIso2: 'NZ',
      countryName: 'New Zealand',
      flagEmoji: '🇳🇿',
      region: 'Oceania',
      portalUrl: 'https://immigration.govt.nz',
      walzFeeUsd: 200, walzFeeNgn: 320000,
      govtFeeUsd: 17, govtFeeAmount: 17, govtFeeCurrency: 'USD',
      processingDaysMin: 5, processingDaysMax: 10,
      maxStayDays: 90, validityDays: 365, singleOrMultiple: 'multiple',
      requiredDocuments: [
        'Valid passport — minimum 3 months beyond intended stay',
        'Passport photograph',
        'Bank statement (3 months)',
        'Employment letter',
        'Return flight booking',
        'Accommodation evidence',
      ],
      jadeTips: 'New Zealand Visitor Visa is processed online. Processing is typically fast. If you hold a valid Australian visa, processing is even quicker. Great destination with high approval rates.',
      commonRefusals: ['Inconsistent financial documents', 'No evidence of return intent'],
      advisoryLevel: 1,
    },
    {
      destinationIso2: 'ZA',
      countryName: 'South Africa',
      flagEmoji: '🇿🇦',
      region: 'Africa',
      portalUrl: 'https://www.vfsglobal.com/southafrica',
      walzFeeUsd: 150, walzFeeNgn: 240000,
      govtFeeUsd: 30, govtFeeAmount: 30, govtFeeCurrency: 'USD',
      processingDaysMin: 7, processingDaysMax: 14,
      maxStayDays: 30, validityDays: 30, singleOrMultiple: 'single',
      requiredDocuments: [
        'Valid passport — minimum 30 days beyond stay',
        '2 passport photographs',
        '3-month bank statement',
        'Employment letter',
        'Yellow fever vaccination (if in transit through endemic country)',
        'Hotel booking confirmation',
        'Return flight booking',
      ],
      jadeTips: 'South Africa visa for Nigerians requires application at VFS Global. Yellow fever vaccination is required if transiting through endemic countries. Allow 2-3 weeks for processing.',
      commonRefusals: ['Missing yellow fever certificate', 'Insufficient bank balance', 'No employment evidence'],
      advisoryLevel: 2,
    },
  ]

  for (const portal of portals) {
    await prisma.countryPortal.upsert({
      where: { destinationIso2: portal.destinationIso2 },
      update: portal,
      create: portal,
    })
    process.stdout.write(`✓ ${portal.flagEmoji} ${portal.countryName}\n`)
  }

  // ── Travel Advisories ────────────────────────────────────────────────────────
  const advisories = [
    { destinationIso2: 'GB', advisoryLevel: 1, advisoryText: 'Exercise normal precautions', message: 'The UK is generally safe for travellers.' },
    { destinationIso2: 'CA', advisoryLevel: 1, advisoryText: 'Exercise normal precautions', message: 'Canada is generally safe for travellers.' },
    { destinationIso2: 'AE', advisoryLevel: 1, advisoryText: 'Exercise normal precautions', message: 'UAE is generally safe. Follow local laws and customs.' },
    { destinationIso2: 'US', advisoryLevel: 1, advisoryText: 'Exercise normal precautions', message: 'The US is generally safe. Be aware of local conditions.' },
    { destinationIso2: 'FR', advisoryLevel: 1, advisoryText: 'Exercise normal precautions', message: 'France is generally safe. Remain vigilant in crowded areas.' },
    { destinationIso2: 'AU', advisoryLevel: 1, advisoryText: 'Exercise normal precautions', message: 'Australia is generally safe.' },
    { destinationIso2: 'NZ', advisoryLevel: 1, advisoryText: 'Exercise normal precautions', message: 'New Zealand is generally safe.' },
    { destinationIso2: 'NG', advisoryLevel: 3, advisoryText: 'Reconsider travel', message: 'Exercise caution due to crime and security concerns in some regions.' },
    { destinationIso2: 'GH', advisoryLevel: 2, advisoryText: 'Exercise increased caution', message: 'Exercise increased caution due to crime.' },
    { destinationIso2: 'EG', advisoryLevel: 2, advisoryText: 'Exercise increased caution', message: 'Exercise increased caution due to terrorism risk.' },
    { destinationIso2: 'TR', advisoryLevel: 2, advisoryText: 'Exercise increased caution', message: 'Exercise increased caution due to terrorism and unrest near borders.' },
    { destinationIso2: 'KE', advisoryLevel: 2, advisoryText: 'Exercise increased caution', message: 'Exercise increased caution due to crime and terrorism threat.' },
    { destinationIso2: 'MA', advisoryLevel: 1, advisoryText: 'Exercise normal precautions', message: 'Morocco is generally safe for tourists.' },
    { destinationIso2: 'ZA', advisoryLevel: 2, advisoryText: 'Exercise increased caution', message: 'Exercise increased caution due to crime, specifically in urban areas.' },
    { destinationIso2: 'IN', advisoryLevel: 2, advisoryText: 'Exercise increased caution', message: 'Exercise increased caution. Petty crime can affect tourists.' },
    { destinationIso2: 'VN', advisoryLevel: 1, advisoryText: 'Exercise normal precautions', message: 'Vietnam is generally safe for travellers.' },
  ]

  for (const advisory of advisories) {
    await prisma.travelAdvisory.upsert({
      where: { destinationIso2: advisory.destinationIso2 },
      update: advisory,
      create: { ...advisory, cachedAt: new Date() },
    })
  }
  console.log(`✓ ${advisories.length} travel advisories seeded`)

  // ── Visa Rules ───────────────────────────────────────────────────────────────
  const rules = [
    // Nigerian passport
    { passportIso2: 'NG', destinationIso2: 'GB', ruleType: 'visa_required', maxDays: 180 },
    { passportIso2: 'NG', destinationIso2: 'CA', ruleType: 'visa_required', maxDays: 180 },
    { passportIso2: 'NG', destinationIso2: 'AE', ruleType: 'visa_required', maxDays: 30 },
    { passportIso2: 'NG', destinationIso2: 'FR', ruleType: 'visa_required', maxDays: 90 },
    { passportIso2: 'NG', destinationIso2: 'US', ruleType: 'visa_required', maxDays: 180 },
    { passportIso2: 'NG', destinationIso2: 'VN', ruleType: 'evisa', maxDays: 90 },
    { passportIso2: 'NG', destinationIso2: 'IN', ruleType: 'evisa', maxDays: 60 },
    { passportIso2: 'NG', destinationIso2: 'TR', ruleType: 'evisa', maxDays: 90 },
    { passportIso2: 'NG', destinationIso2: 'KE', ruleType: 'eta', maxDays: 90 },
    { passportIso2: 'NG', destinationIso2: 'EG', ruleType: 'evisa', maxDays: 30 },
    { passportIso2: 'NG', destinationIso2: 'MA', ruleType: 'visa_required', maxDays: 90 },
    { passportIso2: 'NG', destinationIso2: 'ZA', ruleType: 'visa_required', maxDays: 30 },
    { passportIso2: 'NG', destinationIso2: 'ET', ruleType: 'visa_on_arrival', maxDays: 30 },
    { passportIso2: 'NG', destinationIso2: 'TZ', ruleType: 'evisa', maxDays: 90 },
    { passportIso2: 'NG', destinationIso2: 'UG', ruleType: 'evisa', maxDays: 90 },
    { passportIso2: 'NG', destinationIso2: 'MV', ruleType: 'visa_free', maxDays: 30, notes: 'Free 30-day visa on arrival' },
    { passportIso2: 'NG', destinationIso2: 'SC', ruleType: 'visa_free', maxDays: 30, notes: 'Visa free for tourism' },
    { passportIso2: 'NG', destinationIso2: 'PH', ruleType: 'visa_required', maxDays: 30 },
    { passportIso2: 'NG', destinationIso2: 'AU', ruleType: 'visa_required', maxDays: 90 },
    { passportIso2: 'NG', destinationIso2: 'NZ', ruleType: 'visa_required', maxDays: 90 },
    // Ghanaian passport
    { passportIso2: 'GH', destinationIso2: 'GB', ruleType: 'visa_required', maxDays: 180 },
    { passportIso2: 'GH', destinationIso2: 'CA', ruleType: 'visa_required', maxDays: 180 },
    { passportIso2: 'GH', destinationIso2: 'AE', ruleType: 'visa_required', maxDays: 30 },
    { passportIso2: 'GH', destinationIso2: 'FR', ruleType: 'visa_required', maxDays: 90 },
    { passportIso2: 'GH', destinationIso2: 'US', ruleType: 'visa_required', maxDays: 180 },
    { passportIso2: 'GH', destinationIso2: 'TR', ruleType: 'evisa', maxDays: 90 },
    { passportIso2: 'GH', destinationIso2: 'KE', ruleType: 'eta', maxDays: 90 },
    { passportIso2: 'GH', destinationIso2: 'EG', ruleType: 'evisa', maxDays: 30 },
    { passportIso2: 'GH', destinationIso2: 'MV', ruleType: 'visa_free', maxDays: 30 },
    { passportIso2: 'GH', destinationIso2: 'SC', ruleType: 'visa_free', maxDays: 30 },
    // UK passport
    { passportIso2: 'GB', destinationIso2: 'US', ruleType: 'eta', maxDays: 90, notes: 'ESTA required' },
    { passportIso2: 'GB', destinationIso2: 'AU', ruleType: 'eta', maxDays: 90, notes: 'eVisitor required' },
    { passportIso2: 'GB', destinationIso2: 'IN', ruleType: 'evisa', maxDays: 60 },
    { passportIso2: 'GB', destinationIso2: 'VN', ruleType: 'visa_free', maxDays: 30 },
    { passportIso2: 'GB', destinationIso2: 'TR', ruleType: 'evisa', maxDays: 90 },
    { passportIso2: 'GB', destinationIso2: 'KE', ruleType: 'eta', maxDays: 90 },
    { passportIso2: 'GB', destinationIso2: 'NG', ruleType: 'visa_required', maxDays: 90 },
    { passportIso2: 'GB', destinationIso2: 'GH', ruleType: 'visa_free', maxDays: 90 },
    { passportIso2: 'GB', destinationIso2: 'ZA', ruleType: 'visa_free', maxDays: 30 },
    { passportIso2: 'GB', destinationIso2: 'EG', ruleType: 'visa_on_arrival', maxDays: 30 },
    // US passport
    { passportIso2: 'US', destinationIso2: 'GB', ruleType: 'visa_free', maxDays: 180 },
    { passportIso2: 'US', destinationIso2: 'FR', ruleType: 'visa_free', maxDays: 90 },
    { passportIso2: 'US', destinationIso2: 'AU', ruleType: 'eta', maxDays: 90, notes: 'ETA required' },
    { passportIso2: 'US', destinationIso2: 'IN', ruleType: 'evisa', maxDays: 60 },
    { passportIso2: 'US', destinationIso2: 'VN', ruleType: 'visa_free', maxDays: 45 },
    { passportIso2: 'US', destinationIso2: 'NG', ruleType: 'visa_required', maxDays: 90 },
    { passportIso2: 'US', destinationIso2: 'KE', ruleType: 'eta', maxDays: 90 },
    { passportIso2: 'US', destinationIso2: 'EG', ruleType: 'visa_on_arrival', maxDays: 30 },
    { passportIso2: 'US', destinationIso2: 'TR', ruleType: 'evisa', maxDays: 90 },
    { passportIso2: 'US', destinationIso2: 'ZA', ruleType: 'visa_free', maxDays: 30 },
    { passportIso2: 'US', destinationIso2: 'MA', ruleType: 'visa_free', maxDays: 90 },
  ]

  for (const rule of rules) {
    await prisma.visaRule.upsert({
      where: { passportIso2_destinationIso2: { passportIso2: rule.passportIso2, destinationIso2: rule.destinationIso2 } },
      update: rule,
      create: rule,
    })
  }
  console.log(`✓ ${rules.length} visa rules seeded`)

  // ── Document Guides ──────────────────────────────────────────────────────────
  const guides = [
    {
      visaType: 'visa_required',
      destinationIso2: 'GB',
      documentName: 'Bank Statement',
      whatItIs: 'Official 6-month statement from your commercial bank showing all transactions',
      whyNeeded: 'Proves you have sufficient funds for your trip and strong financial ties to Nigeria',
      whatItMustShow: [
        'Your full name exactly as on passport',
        'Account number clearly shown',
        'All transactions for the past 6 months',
        'Closing balance — minimum NGN 3 million',
        'Bank stamp and authorised signature',
        'Statement dated within the last 30 days',
      ],
      commonMistakes: [
        'Large lump sum deposit just before applying',
        'Statement older than 30 days',
        'Missing bank stamp or authorised signature',
        'Balance below the minimum requirement',
        'Account with no regular transaction history',
      ],
      jadeTip: 'If your balance fluctuates, contact Walz before applying. We have strategies to present your finances in the strongest possible way without misrepresentation.',
    },
    {
      visaType: 'visa_required',
      destinationIso2: 'GB',
      documentName: 'Employment Letter',
      whatItIs: 'Official letter from your employer on company letterhead confirming your employment',
      whyNeeded: 'Proves you have a stable job to return to in Nigeria — a key tie to home country',
      whatItMustShow: [
        'Your full name exactly as on passport',
        'Your current job title',
        'Your monthly or annual salary',
        'Specific approved leave dates',
        'Company letterhead and official stamp',
        'Signed by HR Manager or Director',
        'Letter dated within the last 30 days',
      ],
      commonMistakes: [
        'Missing specific approved leave dates',
        'No company stamp on the letter',
        'Signed by a colleague instead of HR',
        'Salary amount not mentioned',
        'Letter not on official company letterhead',
        'Leave approval not explicitly stated',
      ],
      jadeTip: 'The leave approval dates are critical. Without specific dates shown on the letter, the visa officer cannot verify you will return on time. Request a separate leave approval document if your employment letter cannot include it.',
    },
    {
      visaType: 'visa_required',
      destinationIso2: 'GB',
      documentName: 'Travel Itinerary',
      whatItIs: 'A day-by-day plan of your travel showing where you will be each day',
      whyNeeded: 'Shows the visa officer your trip is planned and purposeful, not open-ended',
      whatItMustShow: [
        'Arrival and departure dates',
        'Cities and towns you plan to visit',
        'Purpose of each day or location',
        'Hotel names and addresses for each night',
        'Any tours, meetings, or events booked',
      ],
      commonMistakes: [
        'Vague itinerary with no specific plans',
        'Dates not matching your flight bookings',
        'Missing accommodation for some nights',
        'Itinerary longer than visa applied for',
      ],
      jadeTip: 'Your itinerary does not need to be rigid — but it must be believable. We help all our UK visa clients prepare a convincing itinerary as part of our service.',
    },
  ]

  for (const guide of guides) {
    await prisma.documentGuide.upsert({
      where: { id: `${guide.destinationIso2}-${guide.documentName.replace(/\s/g, '-').toLowerCase()}` },
      update: guide,
      create: { id: `${guide.destinationIso2}-${guide.documentName.replace(/\s/g, '-').toLowerCase()}`, ...guide },
    })
  }
  console.log(`✓ ${guides.length} document guides seeded`)

  console.log('\n✅ Visa Intelligence Hub seeding complete!')
}

main()
  .catch(e => { console.error('❌ Seed failed:', e); process.exit(1) })
  .finally(() => prisma.$disconnect())
