// lib/portal/portal-jade-tools.ts — Release 6.5: Portal-safe Jade read tools
// userId NEVER appears in any tool schema exposed to the model.
// All ownership verified server-side via PortalToolContext.
// NEVER returns: passport numbers, supplier costs, margins, rateKeys, or admin data.

import prisma from '@/lib/db'
import { getCustomerBookingState, getCustomerBookingStateLabel, getCustomerBookingStateDescription } from './booking-states'
import { getPassportExpiryStatus } from './traveller-dto'
import { deriveCustomerActions } from './customer-actions'

// ─── Tool context ─────────────────────────────────────────────────────────────

export interface PortalToolContext {
  userId: string  // from authenticated session — NEVER from model input
}

// ─── Tool schemas (what the model sees — no userId exposed) ───────────────────

export const PORTAL_JADE_TOOL_SCHEMAS = [
  {
    name: 'get_my_upcoming_trips',
    description: "Get the authenticated customer's upcoming and active trips, including each trip's status and components.",
    input_schema: { type: 'object', properties: {}, required: [] },
  },
  {
    name: 'get_my_trip',
    description: 'Get full details of a specific trip. Only returns trips owned by the authenticated customer.',
    input_schema: {
      type: 'object',
      properties: { tripId: { type: 'string', description: 'The trip ID from a prior get_my_upcoming_trips call' } },
      required: ['tripId'],
    },
  },
  {
    name: 'get_my_bookings',
    description: "Get the authenticated customer's bookings with current status. States: PENDING_PAYMENT, PAYMENT_RECEIVED (payment done but not supplier-confirmed), CONFIRMED, ACTION_REQUIRED, COMPLETED, CANCELLED, REFUND_PROCESSING, REFUNDED, FAILED.",
    input_schema: {
      type: 'object',
      properties: { limit: { type: 'number', description: 'Max results (default 10, max 20)' } },
      required: [],
    },
  },
  {
    name: 'get_my_booking',
    description: 'Get full details of a specific booking. Only returns bookings owned by the authenticated customer. PAYMENT_RECEIVED means payment succeeded but supplier has not yet confirmed — never call this CONFIRMED.',
    input_schema: {
      type: 'object',
      properties: { bookingId: { type: 'string', description: 'The booking ID' } },
      required: ['bookingId'],
    },
  },
  {
    name: 'get_my_proposals',
    description: "Get the authenticated customer's proposals and itineraries from Walz Travels.",
    input_schema: { type: 'object', properties: {}, required: [] },
  },
  {
    name: 'get_my_travellers',
    description: "Get the authenticated customer's traveller profiles. Returns display name, relationship, completeness and passport status only — never passport numbers.",
    input_schema: { type: 'object', properties: {}, required: [] },
  },
  {
    name: 'get_my_notifications',
    description: "Get the authenticated customer's portal notifications.",
    input_schema: {
      type: 'object',
      properties: { unreadOnly: { type: 'boolean', description: 'Return only unread notifications' } },
      required: [],
    },
  },
  {
    name: 'get_my_actions_required',
    description: "Get the list of actions the authenticated customer currently needs to take. These are deterministic server-derived actions — not generated by Jade.",
    input_schema: { type: 'object', properties: {}, required: [] },
  },
] as const

export const PORTAL_JADE_TOOL_NAMES: Set<string> = new Set(PORTAL_JADE_TOOL_SCHEMAS.map(t => t.name))

// ─── Executor ─────────────────────────────────────────────────────────────────

export async function executePortalTool(
  toolName: string,
  toolInput: Record<string, unknown>,
  ctx: PortalToolContext,
): Promise<unknown> {
  const { userId } = ctx  // server-authoritative — never from toolInput

  switch (toolName) {

    case 'get_my_upcoming_trips': {
      const trips = await prisma.trip.findMany({
        where: { userId, status: { notIn: ['CANCELLED', 'COMPLETED'] } },
        orderBy: { updatedAt: 'desc' },
        take: 5,
        include: { items: { orderBy: { order: 'asc' } } },
      })
      return {
        trips: trips.map(t => ({
          id: t.id, title: t.title, destination: t.destination,
          startDate: t.startDate?.toISOString().split('T')[0] ?? null,
          endDate:   t.endDate?.toISOString().split('T')[0] ?? null,
          status: t.status,
          travellers: { adults: t.adults, children: t.children, infants: t.infants },
          itemCount: t.items.length,
          items: t.items.map(i => ({
            id: i.id, type: i.type, title: i.title, confirmed: i.confirmed, location: i.location ?? null,
          })),
        })),
      }
    }

    case 'get_my_trip': {
      const tripId = typeof toolInput.tripId === 'string' ? toolInput.tripId : null
      if (!tripId) return { error: 'tripId is required' }
      const trip = await prisma.trip.findFirst({
        where: { id: tripId, userId },
        include: { items: { orderBy: { order: 'asc' } } },
      })
      if (!trip) return { error: "Trip not found or not accessible to this account." }
      return {
        id: trip.id, title: trip.title, destination: trip.destination,
        startDate: trip.startDate?.toISOString().split('T')[0] ?? null,
        endDate:   trip.endDate?.toISOString().split('T')[0] ?? null,
        status: trip.status, budget: trip.budget, currency: trip.currency,
        travellers: { adults: trip.adults, children: trip.children, infants: trip.infants },
        // trip.notes is customer-entered text — included as data, clearly delimited in prompt
        notes: trip.notes,
        items: trip.items.map(i => ({
          id: i.id, type: i.type, title: i.title, confirmed: i.confirmed,
          location: i.location ?? null,
          startTime: i.startTime ?? null,
          cost: i.cost !== null ? Number(i.cost) : null, currency: i.currency,
          // sourceType/sourceId NOT returned (internal)
        })),
      }
    }

    case 'get_my_bookings': {
      const limit = Math.min(Number(toolInput.limit ?? 10), 20)
      const bookings = await prisma.booking.findMany({
        where: { userId },
        orderBy: { createdAt: 'desc' },
        take: limit,
        select: {
          id: true, bookingReference: true, type: true, status: true,
          paymentStatus: true, totalAmount: true, currency: true, flightDetails: true, createdAt: true,
        },
      })
      return {
        bookings: bookings.map(b => {
          const state = getCustomerBookingState({ status: b.status, paymentStatus: b.paymentStatus })
          const fd = b.flightDetails && typeof b.flightDetails === 'object'
            ? (b.flightDetails as Record<string, unknown>) : null
          return {
            id: b.id,
            reference: b.bookingReference ?? b.id,
            type: b.type,
            state,
            stateLabel: getCustomerBookingStateLabel(state),
            stateDescription: getCustomerBookingStateDescription(state),
            needsAction: state === 'ACTION_REQUIRED',
            amount: Number(b.totalAmount), currency: b.currency,
            route: fd ? [fd.origin, fd.destination].filter(Boolean).join(' → ') : null,
            bookedAt: b.createdAt.toISOString().split('T')[0],
          }
        }),
      }
    }

    case 'get_my_booking': {
      const bookingId = typeof toolInput.bookingId === 'string' ? toolInput.bookingId : null
      if (!bookingId) return { error: 'bookingId is required' }
      const booking = await prisma.booking.findFirst({
        where: { id: bookingId, userId },
        select: {
          id: true, bookingReference: true, pnr: true, type: true,
          status: true, paymentStatus: true, totalAmount: true, currency: true,
          contactEmail: true, contactPhone: true, flightDetails: true, hotelDetails: true,
          passengers: true, createdAt: true,
          // Blocked: notes, fxRate, fxMargin, fareAmount, stripeClientSecret,
          //          cryptoInvoiceId, jadeAssisted, leadId, quoteId, createdByStaffId, branch
        },
      })
      if (!booking) return { error: "Booking not found or not accessible to this account." }
      const state = getCustomerBookingState({ status: booking.status, paymentStatus: booking.paymentStatus })
      const fd = booking.flightDetails && typeof booking.flightDetails === 'object'
        ? (booking.flightDetails as Record<string, unknown>) : null
      const hd = booking.hotelDetails && typeof booking.hotelDetails === 'object'
        ? (booking.hotelDetails as Record<string, unknown>) : null
      const passengers = Array.isArray(booking.passengers)
        ? (booking.passengers as Array<Record<string, unknown>>).map(p => ({
            type: p.type, firstName: p.firstName, lastName: p.lastName,
            // Explicitly excludes: dateOfBirth, passport data
          }))
        : []
      return {
        id: booking.id, reference: booking.bookingReference ?? booking.id, pnr: booking.pnr,
        type: booking.type, state, stateLabel: getCustomerBookingStateLabel(state),
        stateDescription: getCustomerBookingStateDescription(state),
        needsAction: state === 'ACTION_REQUIRED',
        amount: Number(booking.totalAmount), currency: booking.currency,
        flightDetails: fd ? {
          origin: fd.origin, destination: fd.destination,
          outbound: Array.isArray(fd.outbound)
            ? (fd.outbound as Array<Record<string, unknown>>).map(s => ({
                airline: s.airline, flightNumber: s.flightNumber,
                departureAirport: s.departureAirport, arrivalAirport: s.arrivalAirport,
                departureTime: s.departureTime, arrivalTime: s.arrivalTime,
              }))
            : [],
        } : null,
        hotelDetails: hd ? { name: hd.name ?? hd.hotelName, location: hd.location, checkIn: hd.checkIn, checkOut: hd.checkOut } : null,
        passengers,
        bookedAt: booking.createdAt.toISOString().split('T')[0],
      }
    }

    case 'get_my_proposals': {
      const proposals = await prisma.itinerary.findMany({
        where: { userId },
        orderBy: { updatedAt: 'desc' },
        take: 10,
        select: {
          id: true, referenceNumber: true, title: true, destination: true,
          startDate: true, endDate: true, status: true, totalPrice: true,
          currency: true, numberOfTravellers: true, approvedAt: true, sentAt: true,
        },
      })
      return {
        proposals: proposals.map(p => ({
          id: p.id, referenceNumber: p.referenceNumber, title: p.title, destination: p.destination,
          startDate: p.startDate ? new Date(p.startDate).toISOString().split('T')[0] : null,
          endDate:   p.endDate   ? new Date(p.endDate).toISOString().split('T')[0] : null,
          status: p.status, totalPrice: p.totalPrice, currency: p.currency,
          numberOfTravellers: p.numberOfTravellers,
          sentAt:     p.sentAt     ? new Date(p.sentAt).toISOString().split('T')[0] : null,
          approvedAt: p.approvedAt ? new Date(p.approvedAt).toISOString().split('T')[0] : null,
        })),
      }
    }

    case 'get_my_travellers': {
      const [vault, profiles] = await Promise.all([
        prisma.passportVault.findUnique({
          where: { userId },
          select: { givenNames: true, surname: true, nationality: true, sex: true, passportNumber: true, expiryDate: true },
        }).catch(() => null),
        prisma.travellerProfile.findMany({
          where: { userId, isDeleted: false },
          select: { id: true, firstName: true, lastName: true, relationship: true, nationality: true, passportMeta: true },
        }),
      ])
      const result: unknown[] = []
      if (vault) {
        result.push({
          isPrimary: true,
          displayName: [vault.givenNames, vault.surname].filter(Boolean).join(' '),
          relationship: 'Self',
          nationality: vault.nationality,
          passportProvided: !!vault.passportNumber,
          passportExpiry: vault.expiryDate ? vault.expiryDate.toISOString().split('T')[0] : null,
          passportStatus: vault.expiryDate ? getPassportExpiryStatus(vault.expiryDate) : 'NOT_PROVIDED',
          // Explicitly no passport number
        })
      }
      for (const t of profiles) {
        const pm = t.passportMeta && typeof t.passportMeta === 'object' ? (t.passportMeta as Record<string, unknown>) : null
        result.push({
          id: t.id, isPrimary: false,
          displayName: `${t.firstName} ${t.lastName}`.trim(),
          relationship: t.relationship, nationality: t.nationality,
          passportProvided: !!(pm?.maskedNumber),
          passportStatus: pm?.expiryDate ? getPassportExpiryStatus(pm.expiryDate as string) : 'NOT_PROVIDED',
          // Explicitly no passport number or raw passport data
        })
      }
      return { travellers: result }
    }

    case 'get_my_notifications': {
      const unreadOnly = toolInput.unreadOnly === true
      const notifications = await prisma.portalNotification.findMany({
        where: { userId, ...(unreadOnly ? { read: false } : {}) },
        orderBy: { createdAt: 'desc' },
        take: 20,
        select: { id: true, type: true, title: true, body: true, category: true, href: true, read: true, createdAt: true },
      })
      return {
        unreadCount: notifications.filter(n => !n.read).length,
        notifications: notifications.map(n => ({
          id: n.id, type: n.type, title: n.title, body: n.body,
          category: n.category, href: n.href, read: n.read,
          date: n.createdAt.toISOString().split('T')[0],
        })),
      }
    }

    case 'get_my_actions_required': {
      const [appls, props] = await Promise.all([
        prisma.portalApplication.findMany({
          where: { userId },
          select: { id: true, stage: true, title: true, refNumber: true },
          take: 20,
        }).catch(() => [] as Array<{ id: string; stage: string; title: string; refNumber: string }>),
        prisma.itinerary.findMany({
          where: { userId, status: { in: ['sent', 'viewed'] } },
          select: { id: true, status: true, referenceNumber: true, title: true },
          take: 10,
        }),
      ])
      const actions = deriveCustomerActions({
        applications: appls.map(a => ({ id: a.id, stage: a.stage, refNumber: a.refNumber ?? '', title: a.title ?? '' })),
        proposals: props.map(p => ({ id: p.id, referenceNumber: p.referenceNumber, title: p.title, status: p.status })),
      })
      return { actions: actions.map(a => ({ label: a.label, description: a.description, href: a.href, priority: a.priority })) }
    }

    default:
      return { error: `Unknown portal tool: ${toolName}` }
  }
}
